export interface CurrencyOption {
  label: string;
  value: string;
  symbol: string;
}

export const allCurrencies: CurrencyOption[] = [
  { label: "US Dollar (USD)", value: "USD", symbol: "$" },
  { label: "Euro (EUR)", value: "EUR", symbol: "€" },
  { label: "British Pound (GBP)", value: "GBP", symbol: "£" },
  { label: "Japanese Yen (JPY)", value: "JPY", symbol: "¥" },
  { label: "Australian Dollar (AUD)", value: "AUD", symbol: "A$" },
  { label: "Canadian Dollar (CAD)", value: "CAD", symbol: "C$" },
  { label: "Swiss Franc (CHF)", value: "CHF", symbol: "Fr" },
  { label: "Chinese Yuan (CNY)", value: "CNY", symbol: "¥" },
  { label: "Swedish Krona (SEK)", value: "SEK", symbol: "kr" },
  { label: "New Zealand Dollar (NZD)", value: "NZD", symbol: "NZ$" },
  { label: "Mexican Peso (MXN)", value: "MXN", symbol: "Mex$" },
  { label: "Singapore Dollar (SGD)", value: "SGD", symbol: "S$" },
  { label: "Hong Kong Dollar (HKD)", value: "HKD", symbol: "HK$" },
  { label: "Norwegian Krone (NOK)", value: "NOK", symbol: "kr" },
  { label: "South Korean Won (KRW)", value: "KRW", symbol: "₩" },
  { label: "Turkish Lira (TRY)", value: "TRY", symbol: "₺" },
  { label: "Russian Ruble (RUB)", value: "RUB", symbol: "₽" },
  { label: "Indian Rupee (INR)", value: "INR", symbol: "₹" },
  { label: "Brazilian Real (BRL)", value: "BRL", symbol: "R$" },
  { label: "South African Rand (ZAR)", value: "ZAR", symbol: "R" },
  { label: "Philippine Peso (PHP)", value: "PHP", symbol: "₱" },
  { label: "Czech Koruna (CZK)", value: "CZK", symbol: "Kč" },
  { label: "Indonesian Rupiah (IDR)", value: "IDR", symbol: "Rp" },
  { label: "Malaysian Ringgit (MYR)", value: "MYR", symbol: "RM" },
  { label: "Hungarian Forint (HUF)", value: "HUF", symbol: "Ft" },
  { label: "Icelandic Króna (ISK)", value: "ISK", symbol: "kr" },
  { label: "Croatian Kuna (HRK)", value: "HRK", symbol: "kn" },
  { label: "Bulgarian Lev (BGN)", value: "BGN", symbol: "лв" },
  { label: "Romanian Leu (RON)", value: "RON", symbol: "lei" },
  { label: "Danish Krone (DKK)", value: "DKK", symbol: "kr" },
  { label: "Polish Złoty (PLN)", value: "PLN", symbol: "zł" },
  { label: "Israeli New Shekel (ILS)", value: "ILS", symbol: "₪" },
  { label: "Chilean Peso (CLP)", value: "CLP", symbol: "CLP$" },
  { label: "Taiwan New Dollar (TWD)", value: "TWD", symbol: "NT$" },
  { label: "Argentine Peso (ARS)", value: "ARS", symbol: "AR$" },
  { label: "Colombian Peso (COP)", value: "COP", symbol: "COL$" },
  { label: "Saudi Riyal (SAR)", value: "SAR", symbol: "SR" },
  { label: "United Arab Emirates Dirham (AED)", value: "AED", symbol: "AED" },
  { label: "Kuwaiti Dinar (KWD)", value: "KWD", symbol: "KD" },
  { label: "Qatari Riyal (QAR)", value: "QAR", symbol: "QR" },
  { label: "Costa Rican Colón (CRC)", value: "CRC", symbol: "₡" },
  { label: "Dominican Peso (DOP)", value: "DOP", symbol: "RD$" },
  { label: "Uruguayan Peso (UYU)", value: "UYU", symbol: "$U" },
  { label: "Egyptian Pound (EGP)", value: "EGP", symbol: "E£" },
  { label: "Bahraini Dinar (BHD)", value: "BHD", symbol: "BD" },
  { label: "Omani Rial (OMR)", value: "OMR", symbol: "RO" },
  { label: "Jordanian Dinar (JOD)", value: "JOD", symbol: "JD" },
  { label: "Peruvian Sol (PEN)", value: "PEN", symbol: "S/" },
  { label: "Vietnamese Đồng (VND)", value: "VND", symbol: "₫" },
  { label: "Mongolian Tugrik (MNT)", value: "MNT", symbol: "₮" },
  { label: "Nepalese Rupee (NPR)", value: "NPR", symbol: "रू" },
  { label: "Sri Lankan Rupee (LKR)", value: "LKR", symbol: "රු" },
  { label: "Tanzanian Shilling (TZS)", value: "TZS", symbol: "TSh" },
  { label: "Ukrainian Hryvnia (UAH)", value: "UAH", symbol: "₴" },
  { label: "Kenyan Shilling (KES)", value: "KES", symbol: "KSh" },
  { label: "Zambian Kwacha (ZMW)", value: "ZMW", symbol: "ZK" },
  { label: "Mauritian Rupee (MUR)", value: "MUR", symbol: "₨" },
  { label: "Namibian Dollar (NAD)", value: "NAD", symbol: "N$" },
  { label: "Tunisian Dinar (TND)", value: "TND", symbol: "DT" },
  { label: "Moroccan Dirham (MAD)", value: "MAD", symbol: "DH" },
  { label: "Mozambican Metical (MZN)", value: "MZN", symbol: "MT" },
  { label: "Angolan Kwanza (AOA)", value: "AOA", symbol: "Kz" },
  { label: "Guatemalan Quetzal (GTQ)", value: "GTQ", symbol: "Q" },
  { label: "Honduran Lempira (HNL)", value: "HNL", symbol: "L" },
  { label: "Nicaraguan Córdoba (NIO)", value: "NIO", symbol: "C$" },
  { label: "Panamanian Balboa (PAB)", value: "PAB", symbol: "B/." },
  { label: "Paraguayan Guarani (PYG)", value: "PYG", symbol: "₲" },
  { label: "Salvadoran Colón (SVC)", value: "SVC", symbol: "₡" },
  { label: "Belize Dollar (BZD)", value: "BZD", symbol: "BZ$" },
  { label: "Fijian Dollar (FJD)", value: "FJD", symbol: "FJ$" },
  { label: "Guyanese Dollar (GYD)", value: "GYD", symbol: "G$" },
  { label: "Surinamese Dollar (SRD)", value: "SRD", symbol: "SR$" },
  { label: "Trinidad and Tobago Dollar (TTD)", value: "TTD", symbol: "TT$" },
  { label: "East Caribbean Dollar (XCD)", value: "XCD", symbol: "EC$" },
  { label: "Barbadian Dollar (BBD)", value: "BBD", symbol: "Bds$" },
  { label: "Jamaican Dollar (JMD)", value: "JMD", symbol: "J$" },
  { label: "Haitian Gourde (HTG)", value: "HTG", symbol: "G" },
  { label: "Bahamian Dollar (BSD)", value: "BSD", symbol: "B$" },
  { label: "Bermudian Dollar (BMD)", value: "BMD", symbol: "BD$" },
  { label: "Cayman Islands Dollar (KYD)", value: "KYD", symbol: "CI$" },
  { label: "Bermudian Dollar (BMD)", value: "BMD", symbol: "BD$" },

  // ... rest of currencies
]; 